"""add_nombre_column

Revision ID: 9422aebd19f4
Revises: 7791454bbc93
Create Date: 2026-07-28 19:01:29.503701

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9422aebd19f4'
down_revision: Union[str, Sequence[str], None] = '7791454bbc93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('rutinas', 'usuario_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('rutinas', 'icono')
    op.drop_column('rutinas', 'es_publica')
    op.drop_column('rutinas', 'descripcion')
    op.drop_column('rutinas', 'color')
    op.add_column('tareas', sa.Column('xp_otorgada', sa.Boolean(), nullable=False))
    op.add_column('tareas', sa.Column('emoji', sa.String(), nullable=True))
    op.add_column('tareas', sa.Column('repeticion', sa.String(), nullable=True))
    op.add_column('tareas', sa.Column('tiempo_inicio', sa.String(), nullable=True))
    op.add_column('tareas', sa.Column('tiempo_fin', sa.String(), nullable=True))
    op.add_column('tareas', sa.Column('recordatorio_hora', sa.String(), nullable=True))
    op.add_column('tareas', sa.Column('grupo_id', sa.String(), nullable=True))
    op.alter_column('tareas', 'usuario_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('usuarios', sa.Column('nombre', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'nombre')
    op.alter_column('tareas', 'usuario_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('tareas', 'grupo_id')
    op.drop_column('tareas', 'recordatorio_hora')
    op.drop_column('tareas', 'tiempo_fin')
    op.drop_column('tareas', 'tiempo_inicio')
    op.drop_column('tareas', 'repeticion')
    op.drop_column('tareas', 'emoji')
    op.drop_column('tareas', 'xp_otorgada')
    op.add_column('rutinas', sa.Column('color', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('rutinas', sa.Column('descripcion', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('rutinas', sa.Column('es_publica', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('rutinas', sa.Column('icono', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.alter_column('rutinas', 'usuario_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
