{
 "title": "Monitoreo de Contenedores",
 "panels": [
  {
   "title": "Uso de CPU por Contenedor",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{id=~\".*docker.*\"}[5m]) * 100",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "Uso de Memoria por Contenedor",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{id=~\".*docker.*\"}",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "Red Recibida (Bytes/s)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "rate(container_network_receive_bytes_total{id=\"/\"}[5m])",
     "legendFormat": "{{interface}}"
    }
   ]
  },
  {
   "title": "Red Enviada (Bytes/s)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "rate(container_network_transmit_bytes_total{id=\"/\"}[5m])",
     "legendFormat": "{{interface}}"
    }
   ]
  }
 ]
}